In [28]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./datasetes/credit/creditcard.csv", low_memory=False)
# df = pd.read_csv('creditcard.csv', low_memory=False)
df = df.sample(frac=1, random_state=1).reset_index(drop=True)
df.head()

Time        V1        V2        V3        V4        V5        V6  \
0  119907.0 -0.611712 -0.769705 -0.149759 -0.224877  2.028577 -2.019887   
1   78340.0 -0.814682  1.319219  1.329415  0.027273 -0.284871 -0.653985   
2   82382.0 -0.318193  1.118618  0.969864 -0.127052  0.569563 -0.532484   
3   31717.0 -1.328271  1.018378  1.775426 -1.574193 -0.117696 -0.457733   
4   80923.0  1.276712  0.617120 -0.578014  0.879173  0.061706 -1.472002   

         V7        V8        V9  ...         V21       V22       V23  \
0  0.292491 -0.523020  0.358468  ...   -0.075208  0.045536  0.380739   
1  0.321552  0.435975 -0.704298  ...   -0.128619 -0.368565  0.090660   
2  0.706252 -0.064966 -0.463271  ...   -0.305402 -0.774704 -0.123884   
3  0.681867 -0.031641  0.383872  ...   -0.220815 -0.419013 -0.239197   
4  0.373692 -0.287204 -0.084482  ...   -0.160161 -0.430404 -0.076738   

        V24       V25       V26       V27       V28  Amount  Class  
0  0.023440 -2.220686 -0.201146  0.066501  0.221180    1.79      0  
1  0.401147 -0.261034  0.080621  0.162427  0.059456    1.98      0  
2 -0.495687 -0.018148  0.121679  0.249050  0.092516    0.89      0  
3  0.009967  0.232829  0.814177  0.098797 -0.004273   15.98      0  
4  0.258708  0.552170  0.370701 -0.034255  0.041709    0.76      0  

[5 rows x 31 columns]

In [3]:
frauds = df.loc[df['Class'] == 1]
non_frauds = df.loc[df['Class'] == 0]
print("We have", len(frauds), "fraud data points and", len(non_frauds), "nonfraudulent data points.")

We have 492 fraud data points and 284315 nonfraudulent data points.


In [4]:
from sklearn import datasets, linear_model
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split

In [14]:
X = df.iloc[:,:-1]
y = df['Class']

print("X and y sizes, respectively:", len(X), len(y))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=None)
print("Train and test sizes, respectively:", len(X_train), len(y_train), "|", len(X_test), len(y_test))
print("Total number of frauds:", len(y.loc[df['Class'] == 1]), len(y.loc[df['Class'] == 1])/len(y))
print("Number of frauds on y_test:", len(y_test.loc[df['Class'] == 1]), len(y_test.loc[df['Class'] == 1]) / len(y_test))
print("Number of frauds on y_train:", len(y_train.loc[df['Class'] == 1]), len(y_train.loc[df['Class'] == 1])/len(y_train))

X_train = X_train.values
X_test = X_test.values
y_train = y_train.values
y_test = y_test.values

X and y sizes, respectively: 284807 284807
Train and test sizes, respectively: 185124 185124 | 99683 99683
Total number of frauds: 492 0.001727485630620034
Number of frauds on y_test: 177 0.0017756287431156766
Number of frauds on y_train: 315 0.0017015621961496078


In [15]:
X_train[0], y_train[0]

(array([  7.48430000e+04,   9.20057852e-01,  -4.63908476e-01,
         -2.31959978e-02,  -7.41185170e-01,  -5.70499643e-01,
         -1.16636608e+00,   4.75443642e-01,  -2.86845263e-01,
          8.11187361e-01,  -1.10670389e+00,   5.94656279e-01,
          1.26286266e+00,   5.34385763e-01,   4.82157079e-01,
          1.69985497e+00,  -9.86426203e-01,   2.16923206e-01,
         -1.16208258e+00,   2.72781835e-01,   2.12370635e-01,
         -3.00178838e-01,  -1.13251565e+00,   9.58066169e-02,
          3.75061428e-01,   2.14676063e-01,  -1.13629551e+00,
          2.74778087e-02,   5.74272399e-02,   1.70150000e+02]), 0)

In [16]:
X_test[0], y_test[0]

(array([  3.25360000e+04,  -1.26114749e+00,  -5.80602935e-01,
          1.26268088e+00,  -3.34954442e+00,   1.14976627e-01,
         -1.71837611e+00,   9.31607499e-01,  -1.52589961e-01,
          1.41034700e+00,  -2.66945443e+00,   2.34797256e-01,
          1.46343951e+00,   3.35477672e-01,  -3.81444256e-02,
          1.44364718e-01,  -1.20007116e+00,  -7.28258943e-03,
         -9.37097969e-01,  -7.87402434e-01,   1.27134708e-01,
          9.92921934e-02,   1.21770207e-01,   2.39888051e-01,
          6.01294087e-01,   2.00520806e-01,  -1.25487555e+00,
          9.17961830e-02,   1.45483588e-01,   1.17990000e+02]), 0)

In [17]:
train_pd = pd.DataFrame(X_test, columns=['x'+str(i) for i in range(30)])
train_pd['y'] = y_test
train_pd.to_csv("./datasetes/credit/credit_test3.csv", index=False)

In [18]:
train_pd = pd.DataFrame(X_train, columns=['x'+str(i) for i in range(30)])
train_pd['y'] = y_train
train_pd.to_csv("./datasetes/credit/credit_train3.csv", index=False)

In [33]:
from sklearn import metrics

def roc_metrix_mult(a, p, labels=[0,1]):
# #     print(p)
#     if len(set(a)) == 1:
# #         return "acc", metrics.accuracy_score(a, p)
#         return "acc", len(a) - len(np.where(a == p)[0])
#     if type(p) == np.float64 or type(p) == float or type(p) == np.int64 or type(p) == int:
    if len(p.shape) == 1:
        print(type(p), p.shape)
        return "roc", metrics.roc_auc_score(a, p)
#     elif len(p[0]) == 2:
    elif len(p.shape) == 2:
        p = [i[1] for i in p]
        return "roc", metrics.roc_auc_score(a, p)
    else:
        print(type(p), p.shape, "error")

In [63]:
import ModelUtils
import importlib
from collections import Counter
importlib.reload(ModelUtils)

<module 'ModelUtils' from 'C:\\github_workspace\\ecoForest\\ModelUtils.py'>

In [50]:
%%time
ModelUtils.mlp_classifier(X_train, y_train, X_test, y_test, feval=roc_metrix_mult)\

train ('roc', 0.92575724898988376)
test ('roc', 0.92009251692059335)
Wall time: 5.3 s


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [51]:
test_1 = np.array([0.9028, 0.8786, 0.9361, 0.9182, 0.9201])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([ 0.9028,  0.8786,  0.9361,  0.9182,  0.9201]),
 0.019398618507512327,
 0.91116000000000008,
 0.93610000000000004,
 0.87860000000000005)

In [52]:
test_1 = np.array([5.3, 2.95, 5.09, 4.65, 5.3])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([ 5.3 ,  2.95,  5.09,  4.65,  5.3 ]),
 0.88637238224123371,
 4.6580000000000004,
 5.2999999999999998,
 2.9500000000000002)

In [27]:
%%time
ModelUtils.decision_tree(X_train, y_train, X_test, y_test, feval=roc_metrix_mult)

train ('roc', 1.0)
test ('roc', 0.86422588604656148)
Wall time: 11.3 s


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [29]:
test_1 = np.array([0.8671, 0.8529, 0.8557, 0.8699, 0.8529])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([ 0.8671,  0.8529,  0.8557,  0.8699,  0.8529]),
 0.0073113610224088913,
 0.85969999999999991,
 0.86990000000000001,
 0.85289999999999999)

In [31]:
test_1 = np.array([12.4, 12.6, 12.5, 12.4, 12.4])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([ 12.4,  12.6,  12.5,  12.4,  12.4]),
 0.07999999999999971,
 12.459999999999999,
 12.6,
 12.4)

In [39]:
%%time
ModelUtils.random_forest(X_train, y_train, X_test, y_test, n_estimators=200, feval=roc_metrix_mult,\
                         max_depth=3, min_samples_leaf=1, min_samples_split=2)

train ('roc', 1.0)
test ('roc', 0.95223108370037246)
Wall time: 1min 1s


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [40]:
test_1 = np.array([0.9470, 0.9464, 0.9466, 0.9467, 0.9522])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([ 0.947 ,  0.9464,  0.9466,  0.9467,  0.9522]),
 0.0022184679398179487,
 0.94778000000000007,
 0.95220000000000005,
 0.94640000000000002)

In [41]:
test_1 = np.array([1*60+4, 1*60+2, 1*60+1, 59.7, 1*60+1])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([ 64. ,  62. ,  61. ,  59.7,  61. ]),
 1.4305243793798124,
 61.539999999999999,
 64.0,
 59.700000000000003)

In [65]:
%%time
ModelUtils.gdbt_model(X_train, y_train, X_test, y_test, n_estimators=200, feval=roc_metrix_mult)

train ('roc', 0.77133022020933306)
test ('roc', 0.72588777828007067)
Wall time: 5min 3s


GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=200,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [ ]:
train ('roc', 0.77133022020933306)
test ('roc', 0.72588777828007067)
Wall time: 2min 21s
train ('roc', 0.77133022020933306)
test ('roc', 0.72588777828007067)
Wall time: 4min 17s
train ('roc', 0.77133022020933306)
test ('roc', 0.72588777828007067)
Wall time: 4min 53s
train ('roc', 0.77133022020933306)
test ('roc', 0.72588777828007067)
Wall time: 5min 46s
    
train ('roc', 0.94341163234037917)
test ('roc', 0.94337596253657385)
Wall time: 2min 30s
train ('roc', 0.94341163234037917)
test ('roc', 0.94338250617835739)
Wall time: 2min 34s
train ('roc', 0.94341163234037917)
test ('roc', 0.94337596253657385)
Wall time: 2min 25s
    GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=200,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [67]:
test_1 = np.array([0.72578777828007067, 0.72598777828007067, 0.72588777828007067, 0.72588777828007067, 0.72588777828007067])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([ 0.72578778,  0.72598778,  0.72588778,  0.72588778,  0.72588778]),
 6.3245553203360611e-05,
 0.72588777828007067,
 0.72598777828007066,
 0.72578777828007068)

In [66]:
test_1 = np.array([2*60+23, 2*60+21, 2*60+24, 2*60+26, 2*60+14])
test_1, np.std(test_1), np.average(test_1), np.max(test_1), np.min(test_1)

(array([143, 141, 144, 146, 134]),
 4.1279534881100588,
 141.59999999999999,
 146,
 134)

In [57]:
%%time
def roc_metrix(a, p):
    return "roc", metrics.roc_auc_score(a, p)
ModelUtils.xgb_model(X_train, y_train, X_test, y_test, num_class=2, feval=roc_metrix)

{'objective': 'binary:logistic'}
before train
[0]	train-roc:0.912797	valid-roc:0.928431
Multiple eval metrics have been passed: 'valid-roc' will be used for early stopping.

Will train until valid-roc hasn't improved in 500 rounds.
[100]	train-roc:1	valid-roc:0.982731
[200]	train-roc:1	valid-roc:0.983351
[300]	train-roc:1	valid-roc:0.983429
[400]	train-roc:1	valid-roc:0.983811
[500]	train-roc:1	valid-roc:0.983761
[600]	train-roc:1	valid-roc:0.983886
Stopping. Best iteration:
[140]	train-roc:1	valid-roc:0.984089

[  2.07310165e-07   6.92067658e-07   8.01525175e-08 ...,   5.70674530e-09
   1.43014036e-08   1.08651733e-07]
train ('roc', 1.0)
[  1.30800197e-06   1.85992417e-06   5.41658324e-07 ...,   8.89226897e-08
   4.19001616e-08   2.68200750e-07]
test ('roc', 0.9839087154792524)
Wall time: 1min 58s


In [50]:
ModelUtils.baseline_1_flod(X_train, y_train, X_test, y_test, num_class=2, feval=roc_metrix_mult)

X_train.shape, y_train.shape:(185124, 30)(185124,)
X_valid.shape, y_valid.shape:(99683, 30)(99683,)
    cross_score: 0.99932
    test score ('roc', 0.96999061028819533)
<class 'numpy.ndarray'> (99683,)
train kflod pred: ('roc', 0.88732243676163836)
<class 'numpy.ndarray'> (185124,)
train pred ('roc', 0.88382768097794562)
<class 'numpy.ndarray'> (99683,)
test pred ('roc', 0.88732243676163836)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=10, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=-1,
            oob_score=False, random_state=1024, verbose=0,
            warm_start=False)

In [17]:
ModelUtils.baseline_1_flod(X_train, y_train, X_test, y_test, num_class=2, feval=roc_metrix_mult)

X_train.shape, y_train.shape:(185124, 30)(185124,)
X_valid.shape, y_valid.shape:(99683, 30)(99683,)
    cross_score: 0.99945
    test score ('roc', 0.88434784199804484)
train kflod pred: ('roc', 0.88434784199804484)
train pred ('roc', 1.0)
test pred ('roc', 0.88434784199804484)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=-1,
            oob_score=False, random_state=1024, verbose=0,
            warm_start=False)

In [54]:
ModelUtils.baseline_model(X_train, y_train, X_test, y_test, num_class=2, feval=roc_metrix_mult)

X_train.shape, y_train.shape:(123415, 30)(123415,)
X_valid.shape, y_valid.shape:(61709, 30)(61709,)
    cross_score: 0.99938
    test score ('roc', 0.9385198072447446)
X_train.shape, y_train.shape:(123416, 30)(123416,)
X_valid.shape, y_valid.shape:(61708, 30)(61708,)
    cross_score: 0.99947
    test score ('roc', 0.94676463023012292)
X_train.shape, y_train.shape:(123417, 30)(123417,)
X_valid.shape, y_valid.shape:(61707, 30)(61707,)
    cross_score: 0.99922
    test score ('roc', 0.94683779753276531)
<class 'numpy.ndarray'> (185124,)
train kflod pred: ('roc', 0.87090822263499801)
[ 0.00666667  0.00666667  0.00666667 ...,  0.01333333  0.97333333
  0.00666667]
<class 'numpy.ndarray'> (99683,)
test data ('roc', 0.95657020841692353)
<class 'numpy.ndarray'> (185124,)
train pred ('roc', 0.99999452806431022)
[ 0.00666667  0.00666667  0.00666667 ...,  0.01333333  0.96666667
  0.00666667]
<class 'numpy.ndarray'> (99683,)
test pred ('roc', 0.9565711747775244)
train lr shape:  (185124, 2)
<class 

[RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=-1,
             oob_score=False, random_state=1, verbose=0, warm_start=False),
 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=-1,
             oob_score=False, random_state=1, verbose=0, warm_start=False),
 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurit

In [37]:
a = 6
print(type(a))
import numpy as np
type(a) == np.int64

<class 'int'>


False

In [18]:
ModelUtils.baseline_model(X_train, y_train, X_test, y_test, num_class=2, feval=roc_metrix_mult)

X_train.shape, y_train.shape:(148099, 30)(148099,)
X_valid.shape, y_valid.shape:(37025, 30)(37025,)
    cross_score: 0.99914
    test score ('roc', 0.88722796616716715)
X_train.shape, y_train.shape:(148099, 30)(148099,)
X_valid.shape, y_valid.shape:(37025, 30)(37025,)
    cross_score: 0.99927
    test score ('roc', 0.89012818881885403)
X_train.shape, y_train.shape:(148099, 30)(148099,)
X_valid.shape, y_valid.shape:(37025, 30)(37025,)
    cross_score: 0.99949
    test score ('roc', 0.87857251979787665)
X_train.shape, y_train.shape:(148099, 30)(148099,)
X_valid.shape, y_valid.shape:(37025, 30)(37025,)
    cross_score: 0.99935
    test score ('roc', 0.88145264396699896)
X_train.shape, y_train.shape:(148100, 30)(148100,)
X_valid.shape, y_valid.shape:(37024, 30)(37024,)
    cross_score: 0.99938
    test score ('roc', 0.88146269320828119)
train kflod pred: ('roc', 0.89650572971137332)
train pred ('roc', 1.0)
test pred ('roc', 0.88146269320828119)
lr train ('roc', 0.8808425707381643)
lr test 

[RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=-1,
             oob_score=False, random_state=1023, verbose=0,
             warm_start=False),
 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=-1,
             oob_score=False, random_state=1023, verbose=0,
             warm_start=False),
 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=None, max_features='auto', max_leaf_no